name: mtplite-v1.1
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.8.20
  - numpy=1.24.3
  - biopython=1.78
  - xlsxwriter=3.1.1
  - jellyfish=2.2.10
  - hifiasm=0.25.0
  - quast=5.3.0
